export const AppRoutes = {
	HOME: '/',
	LOGIN: '/sign-in',
	RESET_PASSWORD: '/reset-password',
	REGISTER: '/sign-up',
	PROFILE: '/profile/:username',
	READING_LIST: '/readinglist',
	ABOUT: '/about',
	CONTACT: '/contact',
	FAQ: '/faq',
	SPONSORS: '/sponsorship',
	SIGNOUT_CONFIRM: '/signout-confirm',
	FORGOT_PASSWORD: '/users/password/new',
	CONFIRM_OTP: '/users/confirm/otp',
	NEW_PASSWORD: '/users/type-new-password',
	NEW_POST: '/new',
	CODE_OF_CONDUCT: '/code-of-conduct',
	PRIVACY: '/privacy',
	TERMS: '/terms',
  TAGS: '/tags',
	SEARCH: '/search',
	DETAIL_PAGE: '/:username/:slug',
};
